[package]
name = "xmem-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
xmem-core.workspace = true
xmem-pe.workspace = true
xmem-windows.workspace = true
rayon.workspace = true
serde.workspace = true
tracing.workspace = true
